### PR TITLE
fix: adjust catppuccin colors to the correct values

### PR DESCRIPTION
**Pull request by AlphaKeks**
## 📃 Summary

The editor background uses the `base` color of the palette, as defined [here](https://github.com/catppuccin/nvim/blob/55f43a952856bc0029e6cef066297c6cfab3451d/lua/catppuccin/groups/editor.lua#L32). Currently the `crust` values are being used, making the side buffers darker than the main window.

We now provide both color themes.

- [Frappe](https://github.com/catppuccin/nvim/blob/55f43a952856bc0029e6cef066297c6cfab3451d/lua/catppuccin/palettes/frappe.lua#L32)
- [Latte](https://github.com/catppuccin/nvim/blob/55f43a952856bc0029e6cef066297c6cfab3451d/lua/catppuccin/palettes/latte.lua#L32)
- [Macchiato](https://github.com/catppuccin/nvim/blob/55f43a952856bc0029e6cef066297c6cfab3451d/lua/catppuccin/palettes/macchiato.lua#L32)
- [Mocha](https://github.com/catppuccin/nvim/blob/55f43a952856bc0029e6cef066297c6cfab3451d/lua/catppuccin/palettes/mocha.lua#L32)

### CODE REVIEW

**Comment by shortcuts** [comment]
Hey! Thanks for the PR, it was indeed intentional but we can maybe provide both, wdyt?

**Comment by AlphaKeks** [comment]
I'm not sure how you could implement that in a nice way; people probably just want to specify their current theme and be done with it - not decide between 2 variants for each of the 4 available variants. Also the color can be overridden manually, so it's not a difficult "fix" if you prefer a different color. I personally think using the same color makes more sense but I'll let you decide.

**Comment by shortcuts** [comment]
> I'm not sure how you could implement that in a nice way; people probably just want to specify their current theme and be done with it - not decide between 2 variants for each of the 4 available variants. Also the color can be overridden manually, so it's not a difficult "fix" if you prefer a different color. I personally think using the same color makes more sense but I'll let you decide.


it would be super redundant internally, but might still be easier for a user to try every variant than searching for the hex code, e.g. `catppuccin-frappe` or `catppuccin-frappe-dark` and so on

wdyt?

**Comment by AlphaKeks** [comment]
Fair enough.

**Comment by shortcuts** [comment]
looks perfect! I'll generate the doc so we can merge this

**Review by shortcuts — APPROVED** [review]
lovely! thanks again :)

**Pull request merged**
